filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log

  multiline.pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}'
  multiline.negate: true
  multiline.match: after

output.elasticsearch:
  hosts: ["http://elk_elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "kibana:5601"

metrics:
  enabled: false